### ISSUE TITLE
Alternatives/Future Plans?

### ISSUE THREAD

**Issue by hudson-dev** [JensPLarsen/ChromeExtension-GoogleDocsUtil#17]
It seems like this library has lost most of its functionality after Google's update to canvas based rendering. Are there currently any plans to update this library to account for the new update, or are there any alternatives available to use that have the same functionality but work with canvas based rendering?

**Comment by JensPLarsen** [comment]
There are no plans to update this library. 

The most optimistic implementation of a library like this, is as far as I know, a readonly version which can read the HTML screen-reader structure (https://workspaceupdates.googleblog.com/2021/05/Google-Docs-Canvas-Based-Rendering-Update.html --> additional details). 

Otherwise you could look into using OCR.
