### ISSUE TITLE
nodes.lineIndex is always 0 for every node in nodes array

### ISSUE THREAD

**Issue by bboydflo** [JensPLarsen/ChromeExtension-GoogleDocsUtil#8]
when I call `getGoogleDocument` each `node` has `lineIndex: 0`. I think maybe it should be removed since `lineIndex` can be correctly requested from `caret`. Or maybe I missunderstand what `lineIndex` on each node refers to...

**Comment by JensPLarsen** [comment]
The "line index" on the nodes and "line index on the caret" are not the same.
The line index on each node is for bookkeeping. 

A Google Docs document line is build up by nodes.
This is because you can have a line with multiple fonts/sizes/colors/... each way of displaying text will be in its own node. 

Example: 

> Hello **World**

This will be build from 2 nodes, one node for "Hello" and another node for "**World**" (bold).
The node for "Hello" will have a line index of 0 due to it starts the line. But "**World**" will then have a line index of 5 or 6 (depending if the space is bold or not).

If all your text on a given line is the same font/size/color/... , then Google Docs only need one node to show the text. And if all your lines are like this, then all the line indexes for the nodes will be 0.

**Comment by bboydflo** [comment]
It makes sense! Thank you
